- name: Create the folders.
  file:
    path: "{{item}}"
    state: directory
    owner: "0"
    group: "0"
    mode: "0o755"
  loop:
    - "{{server_cert_dir}}"
    - "{{server_key_dir}}"

- name: Copy the server certificate to {{server_cert_dir}}.
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "0"
    group: "0"
    mode: "{{item.mode}}"
  loop:
    - src: vm.local-https.io.pem
      dest: "{{server_cert_dir}}"
      mode: "0o644"
    - src: vm.local-https.io-key.pem
      dest: "{{server_key_dir}}"
      mode: "0o600"

- name: Generate the OpenSSL Diffie-Hellman parameters file.
  block:
    - name: Generate a new OpenSSL Diffie-Hellman parameters file.
      when: not use_existing_dh_param_file
      community.crypto.openssl_dhparam:
        path: /etc/nginx/dhparam0496.pem
        select_crypto_backend: cryptography
        size: 4096
        state: present

    # The DH parameters can be made public.
    # See: https://security.stackexchange.com/a/94397/80050
    - name: Copy the existing OpenSSL Diffie-Hellman parameters file.
      when: use_existing_dh_param_file
      copy:
        src: "dhparam4096.pem"
        dest: "/etc/nginx"
        owner: "0"
        group: "0"
        mode: "0o644"

- name: Copy the nginx configuration files to "/etc/nginx/conf.d".
  copy:
    src: "{{item}}"
    dest: "/etc/nginx/conf.d"
    owner: "0"
    group: "0"
    mode: "0o644"
  loop:
    - local-https.conf
    - local-https-ssl-params.conf
